### ISSUE TITLE
Outil Chrome ItsBetter doesn't find icon

### ISSUE THREAD

**Issue by TitiLaPierre** [devmlb/itsbetter#2]
Traceback (most recent call last):
  File "Outil_Chrome_ItsBetter.py", line 186, in <module>
  File "Outil_Chrome_ItsBetter.py", line 32, in __init__
  File "tkinter\__init__.py", line 2136, in wm_iconbitmap
_tkinter.TclError: bitmap "itsbetter-icon-48.ico" not defined

**Comment by devmlb** [comment]
Le problème d'icône a normalement été corrigé. J'ai mis à jour l'exécutable : https://github.com/devmlb/itsbetter/releases/latest
